# Generated by Django 4.0 on 2022-06-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Заглавие', models.CharField(default=None, max_length=20)),
                ('Сущность', models.CharField(default=None, max_length=300)),
                ('Дата', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новость',
            },
        ),
    ]
