# Generated by Django 4.0 on 2022-06-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='Сущность',
            field=models.TextField(default=None, max_length=300),
        ),
    ]
