# Generated by Django 4.0 on 2022-06-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_сущность'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
