# Generated by Django 4.0 on 2022-06-18 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_is_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='News_slider',
        ),
    ]
