# Generated by Django 4.0 on 2022-06-18 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_rename_news_news_slider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news_slider',
            old_name='Дата',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='news_slider',
            old_name='Заглавие',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='news_slider',
            old_name='Сущность',
            new_name='text',
        ),
    ]
