# Generated by Django 4.0 on 2022-06-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_rename_дата_news_slider_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News_slider_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=20)),
                ('text', models.TextField(default=None, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('is_main', models.BooleanField(default=False, unique=True)),
                ('created', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Новость_1',
                'verbose_name_plural': 'Новости_1',
            },
        ),
        migrations.CreateModel(
            name='News_slider_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=20)),
                ('text', models.TextField(default=None, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('is_main', models.BooleanField(default=False, unique=True)),
                ('created', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Новость_2',
                'verbose_name_plural': 'Новости_2',
            },
        ),
        migrations.CreateModel(
            name='News_slider_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=20)),
                ('text', models.TextField(default=None, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('is_main', models.BooleanField(default=False, unique=True)),
                ('created', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Новость_3',
                'verbose_name_plural': 'Новости_3',
            },
        ),
        migrations.DeleteModel(
            name='News_slider',
        ),
    ]
