# Generated by Django 4.0 on 2022-06-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_news_slider_1_news_slider_2_news_slider_3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news_slider_1',
            name='created',
        ),
        migrations.RemoveField(
            model_name='news_slider_2',
            name='created',
        ),
        migrations.RemoveField(
            model_name='news_slider_3',
            name='created',
        ),
        migrations.AddField(
            model_name='news_slider_1',
            name='data',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='news_slider_2',
            name='data',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='news_slider_3',
            name='data',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
