# Generated by Django 4.0 on 2022-06-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_remove_news_slider_1_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News_slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=20)),
                ('text', models.TextField(default=None, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('data', models.CharField(default=None, max_length=10)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.DeleteModel(
            name='News_slider_1',
        ),
        migrations.DeleteModel(
            name='News_slider_2',
        ),
        migrations.DeleteModel(
            name='News_slider_3',
        ),
    ]
