# Generated by Django 4.0 on 2022-06-30 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_news_slider_delete_news_slider_1_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News_slider',
            new_name='News',
        ),
    ]
