# Generated by Django 4.0 on 2022-06-08 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_articul'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productcategory'),
        ),
    ]
