# Generated by Django 4.0 on 2022-06-08 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_productimage_podcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='podcategory',
        ),
    ]
