# Generated by Django 4.0 on 2022-06-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_remove_product_discount_product_nomera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='nomera',
            field=models.TextField(default=0, max_length=500),
        ),
    ]
