# Generated by Django 4.0 on 2022-08-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_productimage_articul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='articul',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
