# Generated by Django 4.0 on 2022-08-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_alter_productimage_articul'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_metiz',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
