# Generated by Django 4.0 on 2022-08-30 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_alter_product_is_metiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_metiz',
        ),
    ]
