# Generated by Django 4.0 on 2022-08-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_remove_product_is_metiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='is_metiz',
            field=models.BooleanField(default=False),
        ),
    ]
