# Generated by Django 4.0 on 2022-06-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_peoples_delete_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peoples',
            name='Телефон',
            field=models.CharField(default=None, max_length=16),
        ),
    ]
